"""
Tests for point cloud alignment (Option 1 workflow)

Uses synthetic LAZ data generated by conftest fixtures.
Tests in TestAlignmentBasics–TestAlignmentWithTransformation require both PDAL
and small_gicp.  Tests in TestSyntheticAlignment require only small_gicp (they
build numpy arrays directly).
"""

import pytest
import numpy as np
from topochange import PointCloud, PointCloudPair
from topochange.alignment import (
    RegistrationMethod,
    RegistrationConfig,
    LandscapeAligner,
)
from skip_markers import requires_pdal, requires_small_gicp


# ======================================================================
# Tests that exercise the full PointCloudPair alignment path
# (need PDAL to read synthetic LAZ + small_gicp for registration)
# ======================================================================

@requires_pdal
@requires_small_gicp
class TestAlignmentBasics:
    """Tests for basic alignment functionality"""

    def test_align_point_clouds_vgicp(self, pc_pair):
        """Test alignment using VGICP method"""
        align_result = pc_pair.align_point_clouds(
            method="vgicp",
            downsample_resolution=1.0,
            initial_voxel_size=2.0,
            max_points=1_000_000,
        )

        assert align_result is not None
        assert hasattr(align_result, 'transformation')
        assert hasattr(align_result, 'rmse')
        assert hasattr(align_result, 'fitness')
        assert align_result.transformation.shape == (4, 4)
        assert align_result.rmse >= 0
        assert 0.0 <= align_result.fitness <= 1.0

    def test_align_with_memory_constraints(self, pc_pair):
        """Test alignment with memory constraints (larger voxel sizes)"""
        align_result = pc_pair.align_point_clouds(
            method="vgicp",
            downsample_resolution=2.0,
            initial_voxel_size=4.0,
            max_points=500_000,
        )

        assert align_result is not None
        assert align_result.transformation.shape == (4, 4)


@requires_pdal
@requires_small_gicp
class TestAlignmentMethods:
    """Tests for different alignment methods"""

    def test_vgicp_method(self, compare_laz_path, reference_laz_path):
        """Test VGICP method directly via LandscapeAligner"""
        config = RegistrationConfig(
            target_points=100_000,
            max_iterations=50,
        )

        aligner = LandscapeAligner(config)
        result = aligner.align(
            compare_laz_path,
            reference_laz_path,
            method=RegistrationMethod.VGICP,
        )

        assert result is not None
        assert result.transformation.shape == (4, 4)
        assert result.method_used == "vgicp"

    def test_gicp_method(self, compare_laz_path, reference_laz_path):
        """Test GICP method directly"""
        config = RegistrationConfig(
            target_points=100_000,
            max_iterations=50,
        )

        aligner = LandscapeAligner(config)
        result = aligner.align(
            compare_laz_path,
            reference_laz_path,
            method=RegistrationMethod.GICP,
        )

        assert result is not None
        assert result.transformation.shape == (4, 4)
        assert result.method_used == "gicp"

    def test_icp_method(self, compare_laz_path, reference_laz_path):
        """Test ICP method directly"""
        config = RegistrationConfig(
            target_points=100_000,
            max_iterations=50,
        )

        aligner = LandscapeAligner(config)
        result = aligner.align(
            compare_laz_path,
            reference_laz_path,
            method=RegistrationMethod.ICP,
        )

        assert result is not None
        assert result.transformation.shape == (4, 4)
        assert result.method_used == "icp"


@requires_pdal
@requires_small_gicp
class TestAlignmentResults:
    """Tests for alignment result validation"""

    @pytest.fixture
    def alignment_result(self, pc_pair):
        """Create an alignment result for testing"""
        result = pc_pair.align_point_clouds(
            method="vgicp",
            downsample_resolution=1.0,
            max_points=500_000,
        )
        return result

    def test_transformation_matrix_properties(self, alignment_result):
        """Test that transformation matrix has correct properties"""
        T = alignment_result.transformation

        # Should be 4x4
        assert T.shape == (4, 4)

        # Bottom row should be [0, 0, 0, 1]
        assert np.allclose(T[3, :], [0, 0, 0, 1])

        # Upper-left 3x3 should be approximately orthogonal
        R = T[:3, :3]
        RTR = R.T @ R
        assert np.allclose(RTR, np.eye(3), atol=0.1)

    def test_rmse_is_reasonable(self, alignment_result):
        """Test that RMSE is in a reasonable range"""
        assert alignment_result.rmse > 0
        assert alignment_result.rmse < 10.0, (
            f"RMSE {alignment_result.rmse} is unexpectedly high"
        )

    def test_fitness_is_reasonable(self, alignment_result):
        """Test that fitness score is reasonable"""
        fitness = alignment_result.fitness
        assert 0.0 <= fitness <= 1.0
        assert fitness > 0.3, f"Fitness {fitness} is too low"

    def test_convergence(self, alignment_result):
        """Test that alignment converged"""
        assert alignment_result.converged is True


@requires_pdal
@requires_small_gicp
class TestAlignmentConfiguration:
    """Tests for alignment configuration options"""

    def test_custom_downsample_resolution(self, pc_pair):
        """Test alignment with custom downsample resolution"""
        for resolution in [0.5, 1.0, 2.0]:
            result = pc_pair.align_point_clouds(
                method="vgicp",
                downsample_resolution=resolution,
                max_points=500_000,
            )
            assert result is not None
            assert result.transformation.shape == (4, 4)

    def test_custom_max_points(self, pc_pair):
        """Test alignment with custom max points"""
        for max_pts in [100_000, 500_000]:
            result = pc_pair.align_point_clouds(
                method="vgicp",
                downsample_resolution=1.0,
                max_points=max_pts,
            )
            assert result is not None
            assert result.transformation.shape == (4, 4)


@requires_pdal
@requires_small_gicp
class TestAlignmentWithTransformation:
    """Tests for alignment followed by transformation application"""

    def test_alignment_transformation_workflow(self, compare_pc, reference_pc):
        """Test complete alignment and transformation workflow"""
        pc_pair = PointCloudPair(compare_pc, reference_pc)

        result = pc_pair.align_point_clouds(
            method="vgicp",
            downsample_resolution=1.0,
            max_points=500_000,
        )

        assert result is not None
        assert result.converged is True
        assert pc_pair.pc1 is not None


# ======================================================================
# Synthetic tests that only need small_gicp (no PDAL, no LAZ files)
# ======================================================================

class TestSyntheticAlignment:
    """Tests using synthetic numpy arrays with known ground truth.

    These create point clouds programmatically, apply a known
    transformation, and verify the alignment algorithm recovers it.
    Think of it like calibrating a scale with known reference weights.
    """

    def _create_synthetic_terrain(
        self, n_points: int = 50000, seed: int = 42
    ) -> np.ndarray:
        """Rolling-hills terrain as Nx3 float64 array."""
        np.random.seed(seed)
        side = int(np.sqrt(n_points))
        x = np.linspace(0, 100, side)
        y = np.linspace(0, 100, side)
        xx, yy = np.meshgrid(x, y)
        xx = xx.flatten() + np.random.normal(0, 0.1, side * side)
        yy = yy.flatten() + np.random.normal(0, 0.1, side * side)
        zz = (
            5 * np.sin(xx / 10) * np.cos(yy / 10)
            + 2 * np.sin(xx / 3) * np.sin(yy / 5)
            + np.random.normal(0, 0.05, len(xx))
        )
        return np.column_stack([xx, yy, zz]).astype(np.float64)

    def _apply_transformation(
        self,
        points: np.ndarray,
        translation: np.ndarray,
        rotation_deg: float = 0.0,
        rotation_axis: str = "z",
    ) -> np.ndarray:
        """Apply a rigid body transformation to points."""
        angle_rad = np.radians(rotation_deg)
        c, s = np.cos(angle_rad), np.sin(angle_rad)
        if rotation_axis == "z":
            R = np.array([[c, -s, 0], [s, c, 0], [0, 0, 1]])
        elif rotation_axis == "y":
            R = np.array([[c, 0, s], [0, 1, 0], [-s, 0, c]])
        elif rotation_axis == "x":
            R = np.array([[1, 0, 0], [0, c, -s], [0, s, c]])
        else:
            R = np.eye(3)
        return (R @ points.T).T + translation

    @requires_small_gicp
    def test_recovery_of_pure_translation(self):
        """Alignment should recover a known translation."""
        import small_gicp

        target = self._create_synthetic_terrain(n_points=50000, seed=42)
        known_translation = np.array([1.5, -0.8, 0.3])
        source = target + known_translation

        result = small_gicp.align(
            target, source,
            registration_type="GICP",
            downsampling_resolution=0.5,
            max_correspondence_distance=5.0,
            num_threads=4,
        )

        recovered = result.T_target_source[:3, 3]
        expected = -known_translation

        assert result.converged, "Alignment did not converge"
        np.testing.assert_allclose(recovered, expected, atol=0.1)

    @requires_small_gicp
    def test_recovery_of_translation_and_rotation(self):
        """Alignment should recover translation + small rotation."""
        import small_gicp

        target = self._create_synthetic_terrain(n_points=50000, seed=123)
        known_translation = np.array([2.0, 1.0, -0.5])
        known_rotation_deg = 2.0

        source = self._apply_transformation(
            target, known_translation,
            rotation_deg=known_rotation_deg, rotation_axis="z",
        )

        result = small_gicp.align(
            target, source,
            registration_type="GICP",
            downsampling_resolution=0.5,
            max_correspondence_distance=10.0,
            num_threads=4,
        )

        assert result.converged, "Alignment did not converge"

        # Check translation magnitude
        recovered_mag = np.linalg.norm(result.T_target_source[:3, 3])
        expected_mag = np.linalg.norm(known_translation)
        assert abs(recovered_mag - expected_mag) < 0.5

        # Check rotation recovery
        R = result.T_target_source[:3, :3]
        recovered_deg = np.degrees(
            np.arccos(np.clip((np.trace(R) - 1) / 2, -1, 1))
        )
        assert abs(recovered_deg - known_rotation_deg) < 1.0

    @requires_small_gicp
    def test_vgicp_vs_gicp_consistency(self):
        """VGICP and GICP should produce similar results."""
        import small_gicp

        target = self._create_synthetic_terrain(n_points=30000, seed=456)
        known_translation = np.array([1.0, -0.5, 0.2])
        source = target + known_translation

        result_gicp = small_gicp.align(
            target, source,
            registration_type="GICP",
            downsampling_resolution=0.5,
            max_correspondence_distance=5.0,
            num_threads=4,
        )
        result_vgicp = small_gicp.align(
            target, source,
            registration_type="VGICP",
            voxel_resolution=0.5,
            downsampling_resolution=0.5,
            max_correspondence_distance=5.0,
            num_threads=4,
        )

        assert result_gicp.converged
        assert result_vgicp.converged

        np.testing.assert_allclose(
            result_gicp.T_target_source[:3, 3],
            result_vgicp.T_target_source[:3, 3],
            atol=0.2,
        )

    @requires_small_gicp
    def test_alignment_with_partial_overlap(self):
        """Alignment should converge even with only partial overlap."""
        import small_gicp

        np.random.seed(789)
        # Target 0–100 in X
        tx = np.random.uniform(0, 100, 20000)
        ty = np.random.uniform(0, 100, 20000)
        tz = np.sin(tx / 10) + np.cos(ty / 10)
        target = np.column_stack([tx, ty, tz]).astype(np.float64)

        # Source 50–150 in X (50 % overlap) with known offset
        known_translation = np.array([0.5, -0.3, 0.1])
        sx = np.random.uniform(50, 150, 20000)
        sy = np.random.uniform(0, 100, 20000)
        sz = np.sin(sx / 10) + np.cos(sy / 10)
        source = np.column_stack([sx, sy, sz]).astype(np.float64) + known_translation

        result = small_gicp.align(
            target, source,
            registration_type="GICP",
            downsampling_resolution=1.0,
            max_correspondence_distance=10.0,
            num_threads=4,
        )

        assert result.converged
        assert result.num_inliers > 0

    @requires_small_gicp
    def test_identity_alignment(self):
        """Identical clouds should produce near-identity transformation."""
        import small_gicp

        points = self._create_synthetic_terrain(n_points=30000, seed=101)
        target = points.copy()
        source = points.copy() + np.random.normal(0, 0.001, points.shape)

        result = small_gicp.align(
            target, source,
            registration_type="GICP",
            downsampling_resolution=0.5,
            max_correspondence_distance=1.0,
            num_threads=4,
        )

        assert result.converged
        assert np.linalg.norm(result.T_target_source[:3, 3]) < 0.1

        R = result.T_target_source[:3, :3]
        rotation_angle = np.arccos(np.clip((np.trace(R) - 1) / 2, -1, 1))
        assert rotation_angle < np.radians(1.0)


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
